# Generated by Django 5.1.2 on 2024-10-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_aluno_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
    ]
