# Generated by Django 5.1.1 on 2024-10-18 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0002_alter_aluno_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('cpf_resp', models.CharField(max_length=11, unique=True)),
                ('telefone_resp', models.CharField(max_length=20)),
                ('endereco_resp', models.CharField(max_length=100)),
                ('profissao_resp', models.CharField(blank=True, max_length=50, null=True)),
                ('autorizado_resp', models.BooleanField(default=True)),
                ('parentesco_resp', models.CharField(choices=[('Pai', 'Pai'), ('Mãe', 'Mãe')], max_length=20)),
                ('aluno_resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
