# Generated by Django 5.1.1 on 2024-10-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='aluno_resp',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='autorizado_resp',
            new_name='autorizado',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='cpf_resp',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='endereco_resp',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='parentesco_resp',
            new_name='parentesco',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='profissao_resp',
            new_name='profissao',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='telefone_resp',
            new_name='telefone',
        ),
    ]
