# Generated by Django 5.1.1 on 2024-10-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0003_alter_responsavel_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(default='Henrique Siconeli', max_length=50),
            preserve_default=False,
        ),
    ]
