# Generated by Django 5.1.2 on 2024-10-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0006_alter_responsavel_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
