# Generated by Django 5.1.2 on 2024-10-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='aluno',
        ),
    ]
