# Generated by Django 5.1.2 on 2024-10-20 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_remove_aluno_foto'),
        ('documento', '0002_remove_documento_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
            preserve_default=False,
        ),
    ]
