# Generated by Django 5.1.2 on 2024-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_ficha_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='obs',
            field=models.TextField(),
        ),
    ]
