# Generated by Django 5.1.2 on 2024-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_alter_ficha_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='alergico',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='convulsoes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cuidado_especial',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='intolerante',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='quedas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='refluxo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='remedio_continuo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
